# Generated by Django 4.0.3 on 2022-03-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Neighbour',
            new_name='Neighbourhood',
        ),
    ]
