# Generated by Django 4.0.3 on 2022-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='photo',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
