# Generated by Django 4.0.3 on 2022-03-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0006_neighbourhood_image_neighbourhood_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='image',
        ),
    ]
